services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://109.199.110.106:7575
    container_name: daybooker-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://109.199.110.106:7575
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    networks:
      - web_daybooker

networks:
  web_daybooker:
    external: true
